Cherry pick of cfad8ae16020a407c68281d1240ca92c9730df21 failed
stdout:
Auto-merging src/components/selection_input/selection_input.ts
Auto-merging src/plugins/ui_feature/selection_inputs_manager.ts
CONFLICT (content): Merge conflict in src/plugins/ui_feature/selection_inputs_manager.ts
Auto-merging tests/selection_input/selection_input_plugin.test.ts

stderr:
17:53:56.250784 git.c:463               trace: built-in: git cherry-pick cfad8ae16020a407c68281d1240ca92c9730df21
error: could not apply cfad8ae16... [FIX] selection_inputs_manager: arrow keys when broken ranges
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status:

X-original-commit: 89ead135631922f5147c7e828c48075fc5b6b4a3